#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vi='nvim' vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# sudo not required for some system commands
for command in mount umount sv isw vsv pacman dmenugpu nmtui updatedb tlp ps_mem su shutdown poweroff reboot; do
    alias $command="sudo $command"
done
unset command

# vsv-user
alias vsv-user="vsv -d $HOME/.runit/runsvdir"

alias \
    ls="lsd" \
    l="ls -l" \
    la="ls -a" \
    ll="ls -lah" \
    lt="ls --tree"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    q="exit" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    lf="lfub" \
    df="df -h" \
    du="dust -r -n 999999999" \
    tree="tree -aC" \
    free="free -h" \
    info="info --vi-keys" \
    yt="yt-dlp --cookies-from-browser chromium:~/.local/share/qutebrowser --embed-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner" \
    ns="newsboat" \
    nsb="vim ~/.newsboat/bookmarks.txt" \
    cite="cite --style elsevier-vancouver" \
    bibup="betterbib up -i" \
    cman='man -M /usr/share/man/zh_CN' \
    fiji='fiji --system' \
    vv="neovide" \
    powerstat="powerstat -d 5 2"

# wake home nuc
alias wake-nuc="wol -p 9 94:c6:91:17:03:f9"

# Download
alias wget="wget --continue --progress=bar --timestamping"

# mamba
alias mamba="micromamba"

# foam
alias fo10="source $FOAM_INSTALL/OpenFOAM-10/etc/bashrc"

# kitty
alias icat="kitty +kitten icat"

# Permissions aliases
alias \
    664='chmod 664' \
    775='chmod 775'

# buku
alias b='buku --suggest'

#handlr aliases
alias \
    hg='handlr get' \
    hl='handlr list' \
    ha='handlr add' \
    ho='handlr open'

# Colorize commands when possible.
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

#which graphical card is working
alias whichvga="/home/miuka/.local/bin/arcolinux-which-vga"

# taskwarrior
alias \
    t="task list" \
    tt="vit" \
    ta="task add" \
    te="task edit" \
    to="taskopen" \
    ti='task add due:tomorrow tag:inbox'

# Language.
alias \
    mbt="mat cmd" \
    dic="rmall -e -L" \
    ipy="ipython --no-banner --TerminalInteractiveShell.editing_mode=vi" \
    jl="julia --banner no --sysimage=/home/miuka/.julia/sysimage/mysys.so"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall -9" \
    trem="transmission-remote" \
    YT="youtube-viewer" \
    sdn="shutdown -h now" \
    e='$EDITOR' \
    v='$EDITOR' \
    p="pacman" \
    ppy="sudo pacman -Qoq /usr/lib/python3.11" \
    pt="xclip-pastefile" \
    clc="clear" \
    s="pfetch" \
    clashweb="xdg-open http://127.0.0.1:9090/ui >/dev/null 2>&1" \
    printerweb="xdg-open https://localhost:631" \
    bibtex2html="bibtex2html -noheader -nofooter -nobibsource -css ~/.config/bibtex2html/style.css"

alias -g G='| grep -i' # for use ls -l G do
alias cdls="cd && ls"

alias frm="fzf | xargs rm -v"
alias ff='fzf --print0 -e | xargs -0 -r code'

alias chmod755='find . -type d -exec chmod 0755 {} \;'
alias chmod644='find . -type f -exec chmod 0644 {} \;'

alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias npmlist="npm list -g --depth 0"

alias tldrf='tldr --list | fzf  --preview "tldr {1} --color=always" --preview-window=right,70% | xargs tldr'
alias ?='tldrf'
alias ducks='du -chsh * | sort -rn | head -11'
alias wea='curl wttr.in' #check weather
alias bookdl="clibgen search"

#alias nvimb="tabbed -c vimb -e"

alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'

# chopin
alias chopin-open="chopin -o \"\$(fd --type f --hidden --strip-cwd-prefix | fzfpreview --prompt='open>' --select-1 --exit-0)\";exit"
alias chopin-paper="cd '$HOME/papers/pdf/' && chopin -o \"\$(fd -e pdf --strip-cwd-prefix | fzfpreview --prompt='papers>' --select-1 --exit-0)\";exit"
alias chopin-book="cd '$HOME/books/tribology' && chopin -o \"\$(fd -e pdf -e mobi --strip-cwd-prefix | fzfpreview --prompt='books>' --select-1 --exit-0)\";exit"

alias mcamera="mpv --demuxer-lavf-o=video_size=1920x1080,input_format=mjpeg,framerate=25 av://v4l2:/dev/video0 --profile=low-latency"
alias zshconfig='nvim $HOME/.config/zsh/.zshrc'
alias zshreload='source $HOME/.config/zsh/.zshrc && echo "ZSH config reloaded from .zshrc"'

alias hs='history'

# Git Command
alias gst='git status'
alias ga='git add -A'
alias gc='git commit -v'
alias gc!='git commit -v --amend --no-edit'
alias gl='git pull'
alias gp='git push'
alias gp!='git push --force'
alias gcl='git clone --depth 1 --single-branch'
alias gf='git fetch --all'
alias gb='git branch'
alias gd='git diff'
alias gss='git status -s'
alias gt='git checkout'
alias gr='git rebase'
alias lg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gh="xdg-open \`git remote -v | grep fetch | awk '{print \$2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//'\`| head -n1"
alias gg='gstatus /home/miuka/github'
alias gls="\\ls -A --group-directories-first -1 | while IFS= read -r line; do git log --color --format=\"\$(\\ls -d -F --color \"\$line\") =} %C(bold black)▏%Creset%Cred%h %Cgreen(%cr)%Creset =} %C(bold black)▏%Creset%s %C(bold blue)<%an>%Creset\" --abbrev-commit --max-count 1 HEAD -- \"\$line\"; done | awk -F'=}' '{ nf[NR]=NF; for (i = 1; i <= NF; i++) { cell[NR,i] = \$i; gsub(/\\033\\[([[:digit:]]+(;[[:digit:]]+)*)?[mK]/, \"\", \$i); len[NR,i] = l = length(\$i); if (l > max[i]) max[i] = l; } } END { for (row = 1; row <= NR; row++) { for (col = 1; col < nf[row]; col++) printf \"%s%*s%s\", cell[row,col], max[col]-len[row,col], \"\", OFS; print cell[row,nf[row]]; } }'"

# Stow Command
alias stow='stow -v'
alias unstow='stow -D'
alias restow='stow -R'

# vps alias
alias lab='ssh -R 2489:127.0.0.1:2489 lab'
alias jp='ssh -R 2489:127.0.0.1:2489 jp'
alias us='ssh -R 2489:127.0.0.1:2489 us'
alias air='ssh air'
alias nuc='ssh nuc'
alias frpweb='xdg-open http://45.14.107.211:50002/static/'

alias \
    ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc' \
    weath='less -S "$XDG_CACHE_HOME"/weatherreport'
