#!/bin/zsh

FZF_NOTES_DIR="/home/miuka/Documents/Tech_notes"
FZF_PREVIEW_BIN="fzf-notes"
FZF_NOTES_PROMPT="Notes> "
FZF_PREVIEW_LINES="12"
FZF_NOTES_PREVIEW_THRESHOLD="160"
FZF_NOTES_PREVIEW_WINDOW="nohidden|hidden,down"
command -v fzf >/dev/null 2>&1 || return
[ -z "${FZF_NOTES_RG_COMMAND-}" ] && FZF_NOTES_RG_COMMAND="rg \
    --no-column \
    --line-number \
    --no-heading \
    --color=always \
    --colors='match:none' \
    --smart-case \
    -- '\S'"

# Ensure precmds are run after cd.
function fzf_notes_redraw_prompt {
    local precmd
    for precmd in $precmd_functions; do
        $precmd
    done
    zle reset-prompt
}
zle -N fzf_notes_redraw_prompt

function fzf_notes_preview {
    states=("${(s[|])FZF_NOTES_PREVIEW_WINDOW}")
    [ "${#states[@]}" -eq 1 ] && echo "${FZF_NOTES_PREVIEW_WINDOW}" && return
    [ "${#states[@]}" -gt 2 ] && echo "${FZF_NOTES_PREVIEW_WINDOW}" && return
    [ $(tput cols) -lt "${FZF_NOTES_PREVIEW_THRESHOLD}" ] && echo "${states[2]}" && return
    echo "${states[1]}"
}

function fzf_notes {
    local lines=$(eval ${FZF_NOTES_RG_COMMAND} ${FZF_NOTES_DIR} | \
        ${FZF_PREVIEW_BIN} -ns ${FZF_NOTES_DIR} | fzf \
        --prompt "${FZF_NOTES_PROMPT}" \
				--exact \
        --print-query \
        --ansi \
        --delimiter=":" \
        --multi \
        --query="$*" \
        --preview="${FZF_PREVIEW_BIN} -np ${FZF_NOTES_DIR} {1} {2} ${FZF_PREVIEW_LINES}" \
        --preview-window=$(fzf_notes_preview) \
    )
    if [[ -z "$lines" ]]; then
        zle && zle fzf_notes_redraw_prompt
        return 1
    fi

    local key="$(head -n2 <<< "$lines" | tail -n1)"
    if [[ "$key" == "$new_note_key" ]]; then
        fzf_notes_new_entry "$(head -n1 <<< "${lines}")"
    else
        fzf_notes_jump "$(tail -n1 <<< "${lines}")"
    fi
    zle && zle fzf_notes_redraw_prompt || true
}

function fzf_notes_new_entry {
    mkdir -p $(dirname ${FZF_NOTES_DIR}/$1)
    $EDITOR ${FZF_NOTES_DIR}/$1
}

function fzf_notes_jump {
    file=$(cut -d':' -f1 <<< "$1")
    column=$(cut -d':' -f2 <<< "$1")
    # vim compatible editor.
    $EDITOR +$column ${FZF_NOTES_DIR}/$file
}

zle -N fzf_notes

bindkey ${FZF_NOTES_TRIGGER_KEYMAP:-'^n'} fzf_notes
