#!/bin/sh

# start user login session message dbus
# if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
#     export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
#     dbus-daemon --session --fork --address="$DBUS_SESSION_BUS_ADDRESS"
# fi

# Source xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# Activate dbus variables
dbus-update-activation-environment --all

session=${1:-dwm}

case $session in
    dwm) ssh-agent dwm || break ;;
    gnome)
        export XDG_SESSION_TYPE=x11
        export GDK_BACKEND=x11
        ssh-agent gnome-session
        ;;
    xfce)
        ssh-agent startxfce4
        ;;
    cinnamon) ssh-agent gnome-session-cinnamon ;;
    *) ssh-agent $1 ;;
esac
