#!/bin/sh

# xinitrc for xrdp.

remaps &
dunst &
flameshot &
clipmenud &
sxhkd &

eval $(ssh-agent)

# session=${1:-xfce4}
session=${1:-lxde}
# Session=${1:-cinnamon}
# session=${1:-dwm}

case $session in
    dwm) exec dwm ;;
    xfce4)
        export XDG_SESSION_TYPE=x11
        export GDK_BACKEND=x11
        exec xfce4-session
        ;;
    lxde)
        export XDG_SESSION_TYPE=x11
        export GDK_BACKEND=x11
        exec startlxde ;;
    cinnamon)
        exec cinnamon-session ;;
    *) exec $1 ;;
esac

