#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vi='nvim' vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'

# sudo not required for some system commands
for command in mount umount sv pacman nmtui updatedb su shutdown poweroff reboot; do
    alias $command="sudo $command"
done
unset command

alias \
    ls="lsd" \
    l="ls -l" \
    la="ls -a" \
    lla="ls -la" \
    lt="ls --tree"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    q="exit" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    lf="lfrun" \
    df="df -h" \
    yt="yt-dlp --embed-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner" \
    ns="newsboat" \
    nsb="vim ~/.newsboat/bookmarks.txt" \
    sci="scidownl -o ~/Downloads -D" \
    cite="cite --style elsevier-vancouver" \
    bibup="betterbib up -i" \
    cman='man -M /usr/share/man/zh_CN' \
    powerstat="powerstat -d 5 2"

# Download
alias wget="wget --continue --progress=bar --timestamping"

# -- Permissions aliases --
alias \
    664='chmod 664' \
    775='chmod 775'

#handlr aliases
alias \
    hg='handlr get' \
    hl='handlr list' \
    ha='handlr add' \
    ho='handlr open'

# Colorize commands when possible.
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

#which graphical card is working
alias whichvga="/home/miuka/.local/bin/arcolinux-which-vga"

# taskwarrior
alias \
    t="task list" \
    tt="vit" \
    ta="task add" \
    te="task edit" \
    to="taskopen" \
    ti='task add due:tomorrow tag:inbox'

# Language.
alias \
    mat=" matlab -desktop" \
    mbt="matlab -nodesktop -nosplash -r clc" \
    ipy="ipython --no-banner --TerminalInteractiveShell.editing_mode=vi" \
    jl="julia --banner no --sysimage=/home/miuka/.julia/sysimage/sysimage.so"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    g="git" \
    trem="transmission-remote" \
    YT="youtube-viewer" \
    sdn="shutdown -h now" \
    e='$EDITOR' \
    v='$EDITOR' \
    p="pacman" \
    clc="clear" \
    yd="ydict -c -q" \
    s="pfetch" \
    clashweb="xdg-open http://127.0.0.1:9090/ui/" \
    bibtex2html="bibtex2html -noheader -nofooter -nobibsource -css ~/.config/bibtex2html/style.css"

# install list
alias yli="yay -Qq | fzf --multi --preview 'yay -Qi {1}'"
alias yin="yay -Slq | fzf --multi --preview 'yay -Si {1}'"

alias -g G='| grep -i' # for use ls -l G do
alias cdls="cd && ls"

alias frm="fzf | xargs rm -v"
alias ff='fzf --print0 -e | xargs -0 -r code'

alias chmod755='find . -type d -exec chmod 0755 {} \;'
alias chmod644='find . -type f -exec chmod 0644 {} \;'

alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias npmlist="npm list -g --depth 0"
alias grep='grep --colour=auto'

alias ducks='du -chsh * | sort -rn | head -11'
alias wea='curl wttr.in' #check weather
alias bookdl="clibgen search"

#alias nvimb="tabbed -c vimb -e"

alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"

# chopin
alias chopin-open="chopin -o \"\$(fd --type f --hidden --strip-cwd-prefix |fzfpreview --prompt='open>' --select-1 --exit-0)\""
alias chopin-paper="cd '$HOME/papers/pdf/' && chopin -o \"\$(fd -e pdf --strip-cwd-prefix |fzfpreview --prompt='papers>' --select-1 --exit-0)\";exit"
alias chopin-book="cd '$HOME/books/tribology' && chopin -o \"\$(fd -e pdf -e mobi --strip-cwd-prefix |fzfpreview --prompt='books>' --select-1 --exit-0)\";exit"
alias chopin-note="cd '$HOME/notes/Study_Notes' && chopin -o \"\$(fd -e md --strip-cwd-prefix |fzfpreview --prompt='notes>' --select-1 --exit-0)\";exit"
alias chopin-bookmark="cd '$HOME/Documents/bookmark/' && chopin -o \"\$(fd -e pdf --strip-cwd-prefix |fzfpreview --prompt='bookmark>' --select-1 --exit-0)\";exit"

alias mcamera="mpv --demuxer-lavf-o=video_size=1920x1080,input_format=mjpeg,framerate=25 av://v4l2:/dev/video0 --profile=low-latency"
alias zshconfig='nvim $HOME/.config/zsh/.zshrc'
alias zshreload='source $HOME/.config/zsh/.zshrc && echo "ZSH config reloaded from ~/.zshrc"'

alias hs='history'

#live Command
alias tvcn='mpv --hwdec=auto --playlist=/home/miuka/.config/livetv/cctv.m3u --force-seekable=yes'
alias tvjp='mpv --hwdec=auto --playlist=/home/miuka/.config/livetv/jp.m3u --force-seekable=yes'

# Git Command
alias g='git'
alias gl='git clone'
alias gs='git status '
alias gss='git status -s'
alias ga='git add '
alias gb='git branch '
alias gc='git commit '
alias gd='git diff'
alias gt='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias lg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias got='git '
alias get='git '

alias gg='gstatus /home/miuka/github'

# yadm Command
alias y='yadm'
alias ys='yadm status'
alias ya='yadm add'
alias yc='yadm commit'
alias yp='yadm push'

alias \
    ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc' \
    weath='less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport'
