#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Default programs:
export TERMINAL="st"
export WM="dwm"
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="qutebrowser"
export OPENER="xdg-open"
export TFM="lf"
export READER="zathura"
export ZOTOOLS="/home/miuka/.config/zotools/config.json"

# PATH
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export NODE_PATH="$HOME/.local/share/npm/lib/node_modules"
export GOBIN="$GOPATH/bin"
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export JLBIN="$HOME/.julia/bin"
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="$PATH:$GOBIN"
export PATH="$PATH:$JLBIN"
export PATH="$PATH:$GEM_HOME/bin"

unsetopt PROMPT_SP

# export fcitx5 environment variables
export INPUT_METHOD="fcitx5"
export XMODIFIERS="@im=fcitx5"
export GTK_IM_MODULE="fcitx5"
export QT_IM_MODULE="fcitx5"
export SDL_IM_MODULE="fcitx5"


# proxy
#[ -x "$(which clash)" ] && export http_proxy="http://127.0.0.1:7890" && export https_proxy="http://127.0.0.1:7890"

# fix firefox VA-API
export MOZ_DISABLE_RDD_SANDBOX="1"

# julia 
export JULIA_NUM_THREADS=8

# better Java font
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"
export JAVA_FONTS="/usr/share/fonts/TTF"

# Adds to Perl5
export PERL5LIB="$HOME/.local/share/perl5/lib/perl5"
export PERL_LOCAL_LIB_ROOT="$HOME/.local/share/perl5"
export PERL_MB_OPT="--install_base '$HOME/.local/share/perl5'"
export PERL_MM_OPT="INSTALL_BASE=$HOME/.local/share/perl5"

# My Citation:
export BIB="$HOME/papers/bib/mybib.bib"
export CSL="$HOME/papers/bib/tribology-international.csl"

# vulkan
export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/nvidia_icd.json"

# XDG dirs
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DESKTOP_DIR=~

# Home Cleanup
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME:-$HOME/.config}/java"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
export ATOM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/atom"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter"
export MAXIMA_USERDIR="${XDG_CONFIG_HOME:-$HOME/.config}/maxima"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/nv"
export WAKATIME_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wakatime"
export IPYTHONDIR="${XDG_CONFIG_HOME:-$HOME/.config}/ipython"
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonrc"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
export CM_SELECTIONS="clipboard"
export CM_OUTPUT_CLIP=1
export CM_MAX_CLIPS=10

# pfetch
export PF_INFO="ascii title os kernel wm editor shell uptime pkgs memory palette"
export PF_SEP=":"
export PF_COLOR=1

# GPU env
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/gpu" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/gpu"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap 2>/dev/null
