#!/bin/sh

# merge in defaults

# userresources=$HOME/.config/x11/xresources
# if [ -f "$userresources" ]; then
#     xrdb -merge "$userresources"
# fi

# start some nice programs

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

eval $(ssh-agent)

session=${1:-dwm}

# dwm) exec dwm ;;
# dwm) dbus-launch --sh-syntax --exit-with-session dwm ;;
case $session in
    dwm) exec dwm ;;
    gnome)
        export XDG_SESSION_TYPE=x11
        export GDK_BACKEND=x11
        exec gnome-session
        ;;
    cinnamon) exec gnome-session-cinnamon ;;
    *) exec $1 ;;
esac
