#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#pre-setting
#homescreen # NUC
notescreen # laptop
setbg & # set the background
msi-isw #msi ec setting
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps & # run the remaps script, switching caps/esc and more; check it for more info
watchfile &
#autorun conky 

# run user services (run under current user) using runsvdir
runsvdir -P ~/.runit/runsvdir &
runsvdir_pid=$!

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
