#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#pre-setting
#homescreen # NUC
notescreen                                             # laptop
source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/hidpi" # hidpi
setbg &                                                # set the background
xclick &

#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="msi-isw watchfile unclutter blurlock remapd redshift"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# run user services (run under current user) using runsvdir
runsvdir -P ~/.runit/runsvdir &
runsvdir_pid=$!

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
