#!/bin/sh

# Dependency xmenu, xclickroot. Shows a menu on right-click.
# Use tabs. If expandtab is set true, disable it in vim. Space between line gives separator.

xmenu <<EOF | sh &
IMG:$HOME/.config/xmenu/icons/st.svg							Terminal 					st
IMG:$HOME/.config/xmenu/icons/Alacritty.svg							Alacritty 					at
IMG:$HOME/.config/xmenu/icons/openai.svg							GPT4 				google-chrome-stable https://chat.openai.com/
IMG:$HOME/.config/xmenu/icons/rss.svg							Rss 					st -e newsboat
IMG:$HOME/.config/xmenu/icons/zotero.svg							Zotero 					zotero
IMG:$HOME/.config/xmenu/icons/everdo.svg							Todo 	everdo

IMG:$HOME/.config/xmenu/icons/workrave.svg							Application
	Study
		IMG:$HOME/.config/xmenu/icons/wps-word.svg							Word 	wps
		IMG:$HOME/.config/xmenu/icons/wps-ppt.svg							PPT 	wpp
		IMG:$HOME/.config/xmenu/icons/wps-excel.svg							Excel		et
		IMG:$HOME/.config/xmenu/icons/inkscape.svg							Inkscape 	inkscape
		IMG:$HOME/.config/xmenu/icons/ipe.svg							Ipe 	st -e ipe
		IMG:$HOME/.config/xmenu/icons/fiji.svg							Fiji 	fiji --system
		IMG:$HOME/.config/xmenu/icons/obsidian.svg							Obsidian 	obsidian
		IMG:$HOME/.config/xmenu/icons/Zoom.svg							Zoom 	zoom
		IMG:$HOME/.config/xmenu/icons/raindrop.svg							Raindrop 	raindrop
	Music
		IMG:$HOME/.config/xmenu/icons/youtube-music.svg							Youtube-music						youtube-music
		IMG:$HOME/.config/xmenu/icons/cider.svg							Apple-music						cider
	Tools
		IMG:$HOME/.config/xmenu/icons/telegram.svg							Telegram 	telegram-desktop
		IMG:$HOME/.config/xmenu/icons/steam.svg							Steam 	steam
		IMG:$HOME/.config/xmenu/icons/dupeguru.svg							Dupeguru 	QT_SCALE_FACTOR=1.5 dupeguru

IMG:$HOME/.config/xmenu/icons/editor.svg							Edit
	IMG:$HOME/.config/xmenu/icons/tex.svg					Algorithm tex	algo-temp
	IMG:$HOME/.config/xmenu/icons/nvim.svg					dwm config		st -e nvim ~/.local/src/miuka-dwm/config.h
	IMG:$HOME/.config/xmenu/icons/nvim.svg					xmenu config 	st -e nvim ~/.config/xmenu/menu		 
IMG:$HOME/.config/xmenu/icons/heart.svg							Misc
	IMG:$HOME/.config/xmenu/icons/youtube.svg							Youtube 	xdg-open https://www.youtube.com/
	IMG:$HOME/.config/xmenu/icons/bilibili.svg							Bilibili 	xdg-open https://www.bilibili.com/

IMG:$HOME/.config/xmenu/icons/setting.svg							Power Options
	Power off 	poweroff
	Reboot 	 reboot
	Log out 	loginctl terminate-user "$(whoami)"
EOF
