---
## General options
from: markdown+tex_math_single_backslash+wikilinks_title_after_pipe+mark+autolink_bare_uris
to: pdf
# verbosity: ERROR

## Options affecting specific writers
pdf-engine: xelatex
embed-resources: true
listings: true

## General writer options
standalone: true
template: base
dpi: 600
include-in-header:
  - ${.}/include-in-header/caption.tex
# highlight-style: tango

## Reader options
filters:
  - pandoc-crossref
  # - pandoc-include
  - citeproc
  - box.lua
  - diagram-generator.lua

metadata-files:
  - ${.}/metadata/metadata.yaml
  - ${.}/metadata/crossref.yaml
  - ${.}/metadata/listings.yaml
  - ${.}/metadata/plantuml.yaml

## Citation rendering
cite-method: citeproc # citeproc, natbib, or biblatex
bibliography: ${HOME}/papers/bib/mybib_abb.bib
csl: ${HOME}/papers/bib/tribology-international.csl

# input-files:
# - content/ch01.md

## variables
variables:
  # Layout and ConTeXt
  documentclass: scrartcl # article, book, report
  papersize: a4
  fontsize: 12pt
  geometry:
    - left=1.25in
    - right=1in
    - top=1in
    - bottom=1in
    - headheight=3ex
    - headsep=2ex
  # classoption:
  #   - titlepage
  #   - openright
  #   - DIV=calc
  #   - toc=listof
  #   - listof=nochaptergap
  linestretch: 1.15
  # indent: false

  # Metadata variables
  link-citations: true
  link-bibliography: false

  # Links
  colorlinks: true
  linkcolor: blue
  urlcolor: default-urlcolor
  citecolor: blue

  # TOC
  # toc: true
  # toc-depth: 3
  # toc-title:

  # Bib
  biblatexoptions:
  biblio-style:
  biblio-title:
  bibliography:
  natbiboptions:

  # Template variable
  graphics: true
  links-as-notes: false
  listings-disable-line-numbers: false
  listings-no-page-break: true
  ref-title: 'References'
  # zero-width-non-joiner: true
  hyperrefoptions:
    - hidelinks
