matches:
  - trigger: ";smail"
    replace: "zhang.ke.867@s.kyushu-u.ac.jp"
  - trigger: ";gmail"
    replace: "d.lolimiuku@gmail.com"

  # Print the current date
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
