#!/bin/sh
#
RBUKU="$HOME/.local/bin/rbuku"

case "$1" in
    -s)
        url=$($RBUKU -s)
        if [ -n "$url" ]; then
            echo "open $url" >>"$QUTE_FIFO"
        fi
        ;;
    -a) $RBUKU -a "$QUTE_URL" ;;
    -r) $RBUKU -r ;;
    *) $RBUKU ;;
esac
